const fs = require('fs');

const argentinaTeams = [
    {"id": "bocajuniors", "name": "Boca Juniors", "strength": 84, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Boca_Juniors_logo18.svg/200px-Boca_Juniors_logo18.svg.png", "league": "argentina", "balance": 120000000, "stadium": "La Bombonera", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Estadio_Boca_Juniors.jpg/600px-Estadio_Boca_Juniors.jpg"},
    {"id": "riverplate", "name": "River Plate", "strength": 85, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/River_Plate_logo.svg/200px-River_Plate_logo.svg.png", "league": "argentina", "balance": 150000000, "stadium": "Más Monumental", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/River_Plate_stadium.jpg/600px-River_Plate_stadium.jpg"},
    {"id": "racingclub", "name": "Racing Club", "strength": 82, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Racing_Club_logo.svg/200px-Racing_Club_logo.svg.png", "league": "argentina", "balance": 90000000, "stadium": "El Cilindro", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/El_Cilindro_de_Avellaneda.jpg/600px-El_Cilindro_de_Avellaneda.jpg"},
    {"id": "independiente", "name": "Independiente", "strength": 80, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Club_Atl%C3%A9tico_Independiente_logo.svg/200px-Club_Atl%C3%A9tico_Independiente_logo.svg.png", "league": "argentina", "balance": 85000000, "stadium": "Libertadores de América", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Estadio_Libertadores_de_America_2016.jpg/600px-Estadio_Libertadores_de_America_2016.jpg"},
    {"id": "sanlorenzo", "name": "San Lorenzo", "strength": 79, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/San_Lorenzo_de_Almagro_logo.svg/200px-San_Lorenzo_de_Almagro_logo.svg.png", "league": "argentina", "balance": 80000000, "stadium": "Nuevo Gasómetro", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Nuevo_Gasometro_San_Lorenzo.jpg/600px-Nuevo_Gasometro_San_Lorenzo.jpg"},
    {"id": "estudianteslp", "name": "Estudiantes LP", "strength": 81, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Estudiantes_de_La_Plata_logo.svg/200px-Estudiantes_de_La_Plata_logo.svg.png", "league": "argentina", "balance": 75000000, "stadium": "UNO Jorge Luis Hirschi", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Estadio_Jorge_Luis_Hirschi_%28Estudiantes_de_La_Plata%29_vista_a%C3%A9rea.jpg/600px-Estadio_Jorge_Luis_Hirschi_%28Estudiantes_de_La_Plata%29_vista_a%C3%A9rea.jpg"},
    {"id": "talleres", "name": "Talleres", "strength": 81, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Talleres_de_C%C3%B3rdoba_logo.svg/200px-Talleres_de_C%C3%B3rdoba_logo.svg.png", "league": "argentina", "balance": 70000000, "stadium": "Mario Alberto Kempes", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Estadio_Kempes.jpg/600px-Estadio_Kempes.jpg"},
    {"id": "velezsarsfield", "name": "Vélez Sarsfield", "strength": 78, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/V%C3%A9lez_Sarsfield_logo.svg/200px-V%C3%A9lez_Sarsfield_logo.svg.png", "league": "argentina", "balance": 65000000, "stadium": "José Amalfitani", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Estadio_Jose_Amalfitani.jpg/600px-Estadio_Jose_Amalfitani.jpg"},
    {"id": "rosariocentral", "name": "Rosario Central", "strength": 78, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Club_Atletico_Rosario_Central_logo.svg/200px-Club_Atletico_Rosario_Central_logo.svg.png", "league": "argentina", "balance": 60000000, "stadium": "Gigante de Arroyito", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Gigante_de_Arroyito_aereao.jpg/600px-Gigante_de_Arroyito_aereao.jpg"},
    {"id": "newellsoldboys", "name": "Newell's Old Boys", "strength": 77, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Newell%27s_Old_Boys_logo.svg/200px-Newell%27s_Old_Boys_logo.svg.png", "league": "argentina", "balance": 58000000, "stadium": "Marcelo Bielsa", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Estadio_Marcelo_Bielsa_-_Rosario.jpg/600px-Estadio_Marcelo_Bielsa_-_Rosario.jpg"},
    {"id": "argentinosjuniors", "name": "Argentinos Juniors", "strength": 77, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Argentinos_Juniors_logo.svg/200px-Argentinos_Juniors_logo.svg.png", "league": "argentina", "balance": 55000000, "stadium": "Diego Armando Maradona", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Estadio_Diego_Armando_Maradona_AJ.jpg/600px-Estadio_Diego_Armando_Maradona_AJ.jpg"},
    {"id": "lanus", "name": "Lanús", "strength": 76, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Club_Atl%C3%A9tico_Lan%C3%BAs.png/200px-Club_Atl%C3%A9tico_Lan%C3%BAs.png", "league": "argentina", "balance": 50000000, "stadium": "Ciudad de Lanús", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Estadio_Lanus_1.jpg/600px-Estadio_Lanus_1.jpg"},
    {"id": "huracan", "name": "Huracán", "strength": 75, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Hurac%C3%A1n_logo.svg/200px-Hurac%C3%A1n_logo.svg.png", "league": "argentina", "balance": 48000000, "stadium": "Tomás Adolfo Ducó", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Estadio_Tom%C3%A1s_Adolfo_Duc%C3%B3_-_2021.jpg/600px-Estadio_Tom%C3%A1s_Adolfo_Duc%C3%B3_-_2021.jpg"},
    {"id": "defensayjusticia", "name": "Defensa y Justicia", "strength": 76, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Defensa_y_Justicia_logo.svg/200px-Defensa_y_Justicia_logo.svg.png", "league": "argentina", "balance": 45000000, "stadium": "Norberto Tomaghello", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Estadio_Norberto_Tomaghello.jpg/600px-Estadio_Norberto_Tomaghello.jpg"},
    {"id": "belgrano", "name": "Belgrano", "strength": 75, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Club_Atl%C3%A9tico_Belgrano_logo.svg/200px-Club_Atl%C3%A9tico_Belgrano_logo.svg.png", "league": "argentina", "balance": 45000000, "stadium": "Julio César Villagra", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Estadio_Julio_Cesar_Villagra.jpg/600px-Estadio_Julio_Cesar_Villagra.jpg"},
    {"id": "godoycruz", "name": "Godoy Cruz", "strength": 74, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Godoy_Cruz_logo.svg/200px-Godoy_Cruz_logo.svg.png", "league": "argentina", "balance": 40000000, "stadium": "Feliciano Gambarte", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Estadio_Feliciano_Gambarte.jpg/600px-Estadio_Feliciano_Gambarte.jpg"},
    {"id": "banfield", "name": "Banfield", "strength": 73, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Banfield_logo.svg/200px-Banfield_logo.svg.png", "league": "argentina", "balance": 38000000, "stadium": "Florencio Sola", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Estadio_Florencio_Sola.jpg/600px-Estadio_Florencio_Sola.jpg"},
    {"id": "tigre", "name": "Tigre", "strength": 72, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Club_Atl%C3%A9tico_Tigre_logo.svg/200px-Club_Atl%C3%A9tico_Tigre_logo.svg.png", "league": "argentina", "balance": 35000000, "stadium": "José Dellagiovanna", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Estadio_Jose_Dellagiovanna.jpg/600px-Estadio_Jose_Dellagiovanna.jpg"},
    {"id": "union", "name": "Unión", "strength": 72, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Club_Atl%C3%A9tico_Uni%C3%B3n_logo.svg/200px-Club_Atl%C3%A9tico_Uni%C3%B3n_logo.svg.png", "league": "argentina", "balance": 35000000, "stadium": "15 de Abril", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Estadio_15_de_Abril.jpg/600px-Estadio_15_de_Abril.jpg"},
    {"id": "atleticotucuman", "name": "Atlético Tucumán", "strength": 73, "shield": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Atletico_Tucuman_logo.svg/200px-Atletico_Tucuman_logo.svg.png", "league": "argentina", "balance": 35000000, "stadium": "Monumental José Fierro", "stadiumImg": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Estadio_Monumental_Jose_Fierro.jpg/600px-Estadio_Monumental_Jose_Fierro.jpg"}
];

let scriptJs = fs.readFileSync('final/script.js', 'utf8');

if (!scriptJs.includes('"id": "bocajuniors"')) {
    const stringToInject = ',\n' + argentinaTeams.map(t => '    ' + JSON.stringify(t)).join(',\n') + '\n];';
    scriptJs = scriptJs.replace(
        /\];\s*\n*if \(typeof restWorldTeams !== 'undefined'\)/g,
        stringToInject + "\n\nif (typeof restWorldTeams !== 'undefined')"
    );
}

fs.writeFileSync('final/script.js', scriptJs);
console.log('Argentina league injected successfully!');
